version: '3.7'
services:
  admin:
    image: admin
    build: backend
    env_file: backend/.env
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: 'mysql'
    restart: always
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: Admin
      MYSQL_ROOT_PASSWORD: adminPass
      MYSQL_PASSWORD: adminPass
      MYSQL_DATABASE: admindb
      MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: 'true'
