import { MigrationInterface, QueryRunner } from "typeorm";

export class migration1665052409658 implements MigrationInterface {
    name = 'migration1665052409658'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`POS\` DROP FOREIGN KEY \`FK_415d19240c61e4968826d9a0fb6\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP FOREIGN KEY \`FK_5b97b930dfffe8baad191a195f2\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP FOREIGN KEY \`FK_6040a287d03f40eb0cd2d6f6e7e\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP FOREIGN KEY \`FK_618a91852ef8a042edf65be90fc\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP FOREIGN KEY \`FK_8b202431f0c8c76856dc7d144d9\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP FOREIGN KEY \`FK_96665cd89bf5bbabc24e227b5b4\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP FOREIGN KEY \`Merchant_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP FOREIGN KEY \`Merchant_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP FOREIGN KEY \`FK_037082289c0af64352233ba5c70\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP FOREIGN KEY \`FK_88c09574ef9d994db6f868c6eed\``);
        await queryRunner.query(`ALTER TABLE \`Device\` DROP FOREIGN KEY \`FK_160f33da6b221b6e27c5329ac8b\``);
        await queryRunner.query(`ALTER TABLE \`Device\` DROP FOREIGN KEY \`FK_9f77830eeede75246c2dc8a9126\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP FOREIGN KEY \`FK_7b88e1402a75308e106bd32805e\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP FOREIGN KEY \`FK_91fe748b71d25274a2432e4f5e0\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP FOREIGN KEY \`FK_9d8c79453280d689da586e8928d\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP FOREIGN KEY \`FK_cceef50b76ac841f17dc73332f6\``);
        await queryRunner.query(`DROP INDEX \`idStatusFK_MerchantStatus_idx\` ON \`POS\``);
        await queryRunner.query(`DROP INDEX \`IDX_d1a668998e674da9463e6023b4\` ON \`POS\``);
        await queryRunner.query(`DROP INDEX \`idActiveLoyalityFK_Merchant_idx\` ON \`Merchant\``);
        await queryRunner.query(`DROP INDEX \`idEcommerceType_Merchant_idx\` ON \`Merchant\``);
        await queryRunner.query(`DROP INDEX \`idOnlineLoyaltyType_Merchant_idx\` ON \`Merchant\``);
        await queryRunner.query(`DROP INDEX \`idPosFK_Merchant_idx\` ON \`Merchant\``);
        await queryRunner.query(`DROP INDEX \`idStatusFK_MerchantStatus_idx\` ON \`Merchant\``);
        await queryRunner.query(`DROP INDEX \`idsubscription_status\` ON \`Merchant\``);
        await queryRunner.query(`DROP INDEX \`idSubscriptionFK_Merchant_idx\` ON \`Merchant\``);
        await queryRunner.query(`DROP INDEX \`IDX_41b49d9b493397054f3f09ffa9\` ON \`Merchant\``);
        await queryRunner.query(`DROP INDEX \`peronalPhoneNumber_UNIQUE\` ON \`Merchant\``);
        await queryRunner.query(`DROP INDEX \`personalEmail_UNIQUE\` ON \`Merchant\``);
        await queryRunner.query(`DROP INDEX \`idCityFK_Branch_idx\` ON \`Branch\``);
        await queryRunner.query(`DROP INDEX \`idMerchantFK_Branch_idx\` ON \`Branch\``);
        await queryRunner.query(`DROP INDEX \`activationStatusFK_Device_idx\` ON \`Device\``);
        await queryRunner.query(`DROP INDEX \`idBranchFK_Device_idx\` ON \`Device\``);
        await queryRunner.query(`DROP INDEX \`posidbranch_idx\` ON \`Device\``);
        await queryRunner.query(`DROP INDEX \`idCampaignStatusFK_Campaign_idx\` ON \`Campaign\``);
        await queryRunner.query(`DROP INDEX \`idCampaignTypeFK_Campaign_idx\` ON \`Campaign\``);
        await queryRunner.query(`DROP INDEX \`idCityFK_Campaign_idx\` ON \`Campaign\``);
        await queryRunner.query(`DROP INDEX \`idMerchantFK_Campaign_idx\` ON \`Campaign\``);
        await queryRunner.query(CREATE TABLE MerchantCategory (id int NOT NULL AUTO_INCREMENT, enTitle varchar(255) NOT NULL, arTitle varchar(255) NOT NULL, enDescription varchar(255) NOT NULL, arDescription varchar(255) NOT NULL, logo varchar(255) NOT NULL, merchant int NULL, UNIQUE INDEX IDX_a281ff391bd88966c61045b984 (enTitle), UNIQUE INDEX IDX_dd7314684f9c98ce988dd8032d (arTitle), UNIQUE INDEX REL_58ebfb82e26ad991125fa70d34 (merchant), PRIMARY KEY (id)) ENGINE=InnoDB);
        await queryRunner.query(`CREATE TABLE \`pos\` (\`id\` int NOT NULL AUTO_INCREMENT, \`type\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_2c97c531842e5a1f6e1c97c823\` (\`type\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`campaign\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`title_ar\` varchar(255) NOT NULL, \`idCampaignType\` int NOT NULL, \`logo\` varchar(255) NOT NULL, \`idCampaignStatus\` int NOT NULL, \`idMerchantId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`Admin\` DROP COLUMN \`token\``);
        await queryRunner.query(`ALTER TABLE \`POS\` CHANGE \`idPOS\` \`idPOS\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`POS\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`POS\` DROP COLUMN \`idPOS\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`access_token\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`AppSid\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`avg\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`baseVisit\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`bussiness_address\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`coverImageURL\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`cr_name\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`cr_number\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`dashboardData\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`enabled_first_SMS\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`enabled_webhook_order\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`facebookUrl\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`FCMToken\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`hasCustomCampaign\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`hasPickup\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`idActiveLoyality\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`idEcommerceType\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`idLoyaltyType\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`idOnlineLoyaltyType\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`idStatus\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`idSubscription\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`idsubscription_status\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`idSubscriptionPlan\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`instagramUrl\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`integratedPaymentMerchantId\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`intersoftMerchantId\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`isMenuIntegrated\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`isNationalDaySubscribe\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`language\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`max\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`merchant_trn\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`min\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`onlineBillingSubscription\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`onlineConfiguration\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`owner\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`personalEmail\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`personalPhoneNumber\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`pickupNowTime\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`pickupTimes\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`pickupTimes_ar\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`point_valid_days\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`pointScaleFactor\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`posData\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`salt\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`sdkUserNotificationUrl\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`secret\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`senderID\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`snapchatUrl\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`subscription_period\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`subscriptionEndOn\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`subscriptionStartOn\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`theme\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`twitterUrl\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`visits_time_diff\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`phoneNumber\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`posBusinessId\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`token\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`dashboardData\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`discount\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`expirationDate\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`idCity\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`idProduct\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`isDeleted\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`isReward\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`maxOwner\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`newPrice\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`numAvailable\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`numOfValidDays\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`oldPrice\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`posIdBranch\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`posIdProduct\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`priceWithoutVat\``);
        await queryRunner.query(`ALTER TABLE \`Admin\` ADD \`token\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`POS\` ADD \`idPos\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`token\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`phoneNumber\` varchar(14) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`posBusinessId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Admin\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`Admin\` ADD \`email\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Admin\` ADD UNIQUE INDEX \`IDX_fca5840681c3854ea15e03e4a2\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`POS\` CHANGE \`token\` \`token\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`POS\` DROP COLUMN \`posTitle\``);
        await queryRunner.query(`ALTER TABLE \`POS\` ADD \`posTitle\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`POS\` CHANGE \`apiToken\` \`apiToken\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`POS\` CHANGE \`product_integration\` \`product_integration\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`POS\` CHANGE \`product_module\` \`product_module\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD UNIQUE INDEX \`IDX_4ee6f9622e43eaf9f57d90672b\` (\`name\`)`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`name_ar\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`name_ar\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD UNIQUE INDEX \`IDX_9fa80fea402e21078b46abd5cd\` (\`name_ar\`)`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`description_ar\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`description_ar\` varchar(255) NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_76d44e210594dd4ecf817eb425\` ON \`Merchant\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`email\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD UNIQUE INDEX \`IDX_76d44e210594dd4ecf817eb425\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD UNIQUE INDEX \`IDX_5b97b930dfffe8baad191a195f\` (\`idPos\`)`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`idCity\` \`idCity\` int NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`posIdBranch_branch\` \`posIdBranch_branch\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`district\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`district\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`district_ar\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`district_ar\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`managerName\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`managerName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`managerPhoneNumber\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`managerPhoneNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`branch_createdAt\` \`branch_createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`hasPickup\` \`hasPickup\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`isDeleted\` \`isDeleted\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`address\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`location\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`location\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`nameEn\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`nameEn\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`nameAr\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`nameAr\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`idMerchant\` \`idMerchant\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`activationCode\` \`activationCode\` varchar(45) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`posIdBranch\` \`posIdBranch\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`activationStatus\` \`activationStatus\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`token\` \`token\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`deviceModel\` \`deviceModel\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`appVersion\` \`appVersion\` varchar(45) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`deviceOS\` \`deviceOS\` varchar(45) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`deviceOSVersion\` \`deviceOSVersion\` varchar(45) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` DROP COLUMN \`device_createdAt\``);
        await queryRunner.query(`ALTER TABLE \`Device\` ADD \`device_createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`Device\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`Device\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP INDEX \`IDX_4ee6f9622e43eaf9f57d90672b\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD UNIQUE INDEX \`IDX_5b97b930dfffe8baad191a195f\` (\`idPos\`)`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`idCity\` \`idCity\` int NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`branch_createdAt\` \`branch_createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`hasPickup\` \`hasPickup\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`isDeleted\` \`isDeleted\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`workingHr\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`workingHr\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`workingHr_ar\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`workingHr_ar\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`idMerchant\` \`idMerchant\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`POS\` CHANGE \`token\` \`token\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`POS\` CHANGE \`apiToken\` \`apiToken\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`POS\` CHANGE \`product_integration\` \`product_integration\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`POS\` CHANGE \`product_module\` \`product_module\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD UNIQUE INDEX \`IDX_5b97b930dfffe8baad191a195f\` (\`idPos\`)`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`idCity\` \`idCity\` int NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`posIdBranch_branch\` \`posIdBranch_branch\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`branch_createdAt\` \`branch_createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`hasPickup\` \`hasPickup\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`isDeleted\` \`isDeleted\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`workingHr\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`workingHr\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`workingHr_ar\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`workingHr_ar\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`idMerchant\` \`idMerchant\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`activationCode\` \`activationCode\` varchar(45) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`posIdBranch\` \`posIdBranch\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`activationStatus\` \`activationStatus\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`token\` \`token\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`deviceModel\` \`deviceModel\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`appVersion\` \`appVersion\` varchar(45) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`deviceOS\` \`deviceOS\` varchar(45) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`deviceOSVersion\` \`deviceOSVersion\` varchar(45) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`title\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`title\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`title_ar\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`title_ar\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` CHANGE \`idCampaignStatus\` \`idCampaignStatus\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`description\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`description_ar\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`description_ar\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` CHANGE \`idMerchant\` \`idMerchant\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`idCity\` \`idCity\` int NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`posIdBranch_branch\` \`posIdBranch_branch\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`branch_createdAt\` \`branch_createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`hasPickup\` \`hasPickup\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`isDeleted\` \`isDeleted\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`idMerchant\` \`idMerchant\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` CHANGE \`idCampaignStatus\` \`idCampaignStatus\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` CHANGE \`idMerchant\` \`idMerchant\` int NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_4ee6f9622e43eaf9f57d90672b\` ON \`Merchant\` (\`name\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_5b97b930dfffe8baad191a195f\` ON \`Merchant\` (\`idPos\`)`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD CONSTRAINT \`FK_5b97b930dfffe8baad191a195f2\` FOREIGN KEY (\`idPos\`) REFERENCES \`POS\`(\`idPos\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`MerchantCategory\` ADD CONSTRAINT \`FK_58ebfb82e26ad991125fa70d34c\` FOREIGN KEY (\`merchant\`) REFERENCES \`Merchant\`(\`idMerchant\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD CONSTRAINT \`FK_037082289c0af64352233ba5c70\` FOREIGN KEY (\`idMerchant\`) REFERENCES \`Merchant\`(\`idMerchant\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Device\` ADD CONSTRAINT \`FK_9f77830eeede75246c2dc8a9126\` FOREIGN KEY (\`idBranch\`) REFERENCES \`Branch\`(\`idBranch\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD CONSTRAINT \`FK_5b97b930dfffe8baad191a195f2\` FOREIGN KEY (\`idPos\`) REFERENCES \`pos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`campaign\` ADD CONSTRAINT \`FK_5ccdb6e10d68e22c2acabe5a7b5\` FOREIGN KEY (\`idMerchantId\`) REFERENCES \`Merchant\`(\`idMerchant\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD CONSTRAINT \`FK_91fe748b71d25274a2432e4f5e0\` FOREIGN KEY (\`idMerchant\`) REFERENCES \`Merchant\`(\`idMerchant\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP FOREIGN KEY \`FK_91fe748b71d25274a2432e4f5e0\``);
        await queryRunner.query(`ALTER TABLE \`campaign\` DROP FOREIGN KEY \`FK_5ccdb6e10d68e22c2acabe5a7b5\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP FOREIGN KEY \`FK_5b97b930dfffe8baad191a195f2\``);
        await queryRunner.query(`ALTER TABLE \`Device\` DROP FOREIGN KEY \`FK_9f77830eeede75246c2dc8a9126\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP FOREIGN KEY \`FK_037082289c0af64352233ba5c70\``);
        await queryRunner.query(`ALTER TABLE \`MerchantCategory\` DROP FOREIGN KEY \`FK_58ebfb82e26ad991125fa70d34c\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP FOREIGN KEY \`FK_5b97b930dfffe8baad191a195f2\``);
        await queryRunner.query(`DROP INDEX \`REL_5b97b930dfffe8baad191a195f\` ON \`Merchant\``);
        await queryRunner.query(`DROP INDEX \`IDX_4ee6f9622e43eaf9f57d90672b\` ON \`Merchant\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` CHANGE \`idMerchant\` \`idMerchant\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` CHANGE \`idCampaignStatus\` \`idCampaignStatus\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`idMerchant\` \`idMerchant\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`isDeleted\` \`isDeleted\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`hasPickup\` \`hasPickup\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`branch_createdAt\` \`branch_createdAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`posIdBranch_branch\` \`posIdBranch_branch\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`idCity\` \`idCity\` int NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` CHANGE \`idMerchant\` \`idMerchant\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`description_ar\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`description_ar\` text COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`description\` text COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` CHANGE \`idCampaignStatus\` \`idCampaignStatus\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`title_ar\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`title_ar\` varchar(45) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` DROP COLUMN \`title\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`title\` varchar(45) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`deviceOSVersion\` \`deviceOSVersion\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`deviceOS\` \`deviceOS\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`appVersion\` \`appVersion\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`deviceModel\` \`deviceModel\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`token\` \`token\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'test'`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`activationStatus\` \`activationStatus\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`posIdBranch\` \`posIdBranch\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`activationCode\` \`activationCode\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`idMerchant\` \`idMerchant\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`workingHr_ar\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`workingHr_ar\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`workingHr\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`workingHr\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`isDeleted\` \`isDeleted\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`hasPickup\` \`hasPickup\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`branch_createdAt\` \`branch_createdAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`posIdBranch_branch\` \`posIdBranch_branch\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`idCity\` \`idCity\` int NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP INDEX \`IDX_5b97b930dfffe8baad191a195f\``);
        await queryRunner.query(`ALTER TABLE \`POS\` CHANGE \`product_module\` \`product_module\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`POS\` CHANGE \`product_integration\` \`product_integration\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`POS\` CHANGE \`apiToken\` \`apiToken\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`POS\` CHANGE \`token\` \`token\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`idMerchant\` \`idMerchant\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`workingHr_ar\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`workingHr_ar\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`workingHr\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`workingHr\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`isDeleted\` \`isDeleted\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`hasPickup\` \`hasPickup\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`branch_createdAt\` \`branch_createdAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`idCity\` \`idCity\` int NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP INDEX \`IDX_5b97b930dfffe8baad191a195f\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD UNIQUE INDEX \`IDX_4ee6f9622e43eaf9f57d90672b\` (\`name\`)`);
        await queryRunner.query(`ALTER TABLE \`Device\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`Device\` ADD \`updatedAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`Device\` DROP COLUMN \`device_createdAt\``);
        await queryRunner.query(`ALTER TABLE \`Device\` ADD \`device_createdAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`deviceOSVersion\` \`deviceOSVersion\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`deviceOS\` \`deviceOS\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`appVersion\` \`appVersion\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`deviceModel\` \`deviceModel\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`token\` \`token\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'test'`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`activationStatus\` \`activationStatus\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`posIdBranch\` \`posIdBranch\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Device\` CHANGE \`activationCode\` \`activationCode\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`idMerchant\` \`idMerchant\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`nameAr\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`nameAr\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`nameEn\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`nameEn\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`location\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`location\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`address\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`address\` text COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`isDeleted\` \`isDeleted\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`hasPickup\` \`hasPickup\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`branch_createdAt\` \`branch_createdAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`managerPhoneNumber\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`managerPhoneNumber\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`managerName\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`managerName\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`district_ar\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`district_ar\` varchar(45) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'الموقع'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` DROP COLUMN \`district\``);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD \`district\` varchar(45) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'Test'`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`posIdBranch_branch\` \`posIdBranch_branch\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Branch\` CHANGE \`idCity\` \`idCity\` int NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP INDEX \`IDX_5b97b930dfffe8baad191a195f\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`createdAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP INDEX \`IDX_76d44e210594dd4ecf817eb425\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`email\` varchar(45) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_76d44e210594dd4ecf817eb425\` ON \`Merchant\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`description_ar\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`description_ar\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP INDEX \`IDX_9fa80fea402e21078b46abd5cd\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`name_ar\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`name_ar\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP INDEX \`IDX_4ee6f9622e43eaf9f57d90672b\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`name\` varchar(45) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`POS\` CHANGE \`product_module\` \`product_module\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`POS\` CHANGE \`product_integration\` \`product_integration\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`POS\` CHANGE \`apiToken\` \`apiToken\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`POS\` DROP COLUMN \`posTitle\``);
        await queryRunner.query(`ALTER TABLE \`POS\` ADD \`posTitle\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`POS\` CHANGE \`token\` \`token\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Admin\` DROP INDEX \`IDX_fca5840681c3854ea15e03e4a2\``);
        await queryRunner.query(`ALTER TABLE \`Admin\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`Admin\` ADD \`email\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`posBusinessId\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`phoneNumber\``);
        await queryRunner.query(`ALTER TABLE \`Merchant\` DROP COLUMN \`token\``);
        await queryRunner.query(`ALTER TABLE \`POS\` DROP COLUMN \`idPos\``);
        await queryRunner.query(`ALTER TABLE \`Admin\` DROP COLUMN \`token\``);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`priceWithoutVat\` decimal NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`posIdProduct\` text COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`posIdBranch\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`oldPrice\` decimal NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`numOfValidDays\` int NULL DEFAULT '365'`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`numAvailable\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`newPrice\` decimal NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`maxOwner\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`isReward\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`isDeleted\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`idProduct\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`idCity\` int NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`expirationDate\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`discount\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`dashboardData\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`token\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'test'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`posBusinessId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`phoneNumber\` varchar(14) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`visits_time_diff\` int NOT NULL DEFAULT '5'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`twitterUrl\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`theme\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`subscriptionStartOn\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`subscriptionEndOn\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`subscription_period\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`snapchatUrl\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`senderID\` varchar(200) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`secret\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`sdkUserNotificationUrl\` text COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`salt\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'test'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`posData\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`pointScaleFactor\` tinyint NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`point_valid_days\` int NOT NULL DEFAULT '90'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`pickupTimes_ar\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`pickupTimes\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`pickupNowTime\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`personalPhoneNumber\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`personalEmail\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`owner\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`onlineConfiguration\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`onlineBillingSubscription\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`min\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`merchant_trn\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`max\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`language\` varchar(4) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`isNationalDaySubscribe\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`isMenuIntegrated\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`intersoftMerchantId\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`integratedPaymentMerchantId\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`instagramUrl\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`idSubscriptionPlan\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`idsubscription_status\` int NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`idSubscription\` int NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`idStatus\` int NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`idOnlineLoyaltyType\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`idLoyaltyType\` tinyint NOT NULL DEFAULT '2'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`idEcommerceType\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`idActiveLoyality\` varchar(50) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`hasPickup\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`hasCustomCampaign\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`FCMToken\` text COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`facebookUrl\` varchar(45) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`enabled_webhook_order\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`enabled_first_SMS\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`dashboardData\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`cr_number\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`cr_name\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`coverImageURL\` text COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`bussiness_address\` text COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`baseVisit\` int NOT NULL DEFAULT '7'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`avg\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`AppSid\` text COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD \`access_token\` text COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`POS\` ADD \`idPOS\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`POS\` ADD PRIMARY KEY (\`idPOS\`)`);
        await queryRunner.query(`ALTER TABLE \`POS\` CHANGE \`idPOS\` \`idPOS\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Admin\` ADD \`token\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`DROP TABLE \`campaign\``);
        await queryRunner.query(`DROP INDEX \`IDX_2c97c531842e5a1f6e1c97c823\` ON \`pos\``);
        await queryRunner.query(`DROP TABLE \`pos\``);
        await queryRunner.query(`DROP INDEX \`REL_58ebfb82e26ad991125fa70d34\` ON \`MerchantCategory\``);
        await queryRunner.query(`DROP INDEX \`IDX_dd7314684f9c98ce988dd8032d\` ON \`MerchantCategory\``);
        await queryRunner.query(`DROP INDEX \`IDX_a281ff391bd88966c61045b984\` ON \`MerchantCategory\``);
        await queryRunner.query(`DROP TABLE \`MerchantCategory\``);
        await queryRunner.query(`CREATE INDEX \`idMerchantFK_Campaign_idx\` ON \`Campaign\` (\`idMerchant\`)`);
        await queryRunner.query(`CREATE INDEX \`idCityFK_Campaign_idx\` ON \`Campaign\` (\`idCity\`)`);
        await queryRunner.query(`CREATE INDEX \`idCampaignTypeFK_Campaign_idx\` ON \`Campaign\` (\`idCampaignType\`)`);
        await queryRunner.query(`CREATE INDEX \`idCampaignStatusFK_Campaign_idx\` ON \`Campaign\` (\`idCampaignStatus\`)`);
        await queryRunner.query(`CREATE INDEX \`posidbranch_idx\` ON \`Device\` (\`posIdBranch\`)`);
        await queryRunner.query(`CREATE INDEX \`idBranchFK_Device_idx\` ON \`Device\` (\`idBranch\`)`);
        await queryRunner.query(`CREATE INDEX \`activationStatusFK_Device_idx\` ON \`Device\` (\`activationStatus\`)`);
        await queryRunner.query(`CREATE INDEX \`idMerchantFK_Branch_idx\` ON \`Branch\` (\`idMerchant\`)`);
        await queryRunner.query(`CREATE INDEX \`idCityFK_Branch_idx\` ON \`Branch\` (\`idCity\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`personalEmail_UNIQUE\` ON \`Merchant\` (\`personalEmail\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`peronalPhoneNumber_UNIQUE\` ON \`Merchant\` (\`personalPhoneNumber\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_41b49d9b493397054f3f09ffa9\` ON \`Merchant\` (\`phoneNumber\`)`);
        await queryRunner.query(`CREATE INDEX \`idSubscriptionFK_Merchant_idx\` ON \`Merchant\` (\`idSubscription\`)`);
        await queryRunner.query(`CREATE INDEX \`idsubscription_status\` ON \`Merchant\` (\`idsubscription_status\`)`);
        await queryRunner.query(`CREATE INDEX \`idStatusFK_MerchantStatus_idx\` ON \`Merchant\` (\`idStatus\`)`);
        await queryRunner.query(`CREATE INDEX \`idPosFK_Merchant_idx\` ON \`Merchant\` (\`idPos\`)`);
        await queryRunner.query(`CREATE INDEX \`idOnlineLoyaltyType_Merchant_idx\` ON \`Merchant\` (\`idOnlineLoyaltyType\`)`);
        await queryRunner.query(`CREATE INDEX \`idEcommerceType_Merchant_idx\` ON \`Merchant\` (\`idEcommerceType\`)`);
        await queryRunner.query(`CREATE INDEX \`idActiveLoyalityFK_Merchant_idx\` ON \`Merchant\` (\`idActiveLoyality\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_d1a668998e674da9463e6023b4\` ON \`POS\` (\`token\`)`);
        await queryRunner.query(`CREATE INDEX \`idStatusFK_MerchantStatus_idx\` ON \`POS\` (\`idStatus\`)`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD CONSTRAINT \`FK_cceef50b76ac841f17dc73332f6\` FOREIGN KEY (\`idCity\`) REFERENCES \`City\`(\`idCity\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD CONSTRAINT \`FK_9d8c79453280d689da586e8928d\` FOREIGN KEY (\`idCampaignStatus\`) REFERENCES \`CampaignStatus\`(\`idCampaignStatus\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD CONSTRAINT \`FK_91fe748b71d25274a2432e4f5e0\` FOREIGN KEY (\`idMerchant\`) REFERENCES \`Merchant\`(\`idMerchant\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`Campaign\` ADD CONSTRAINT \`FK_7b88e1402a75308e106bd32805e\` FOREIGN KEY (\`idCampaignType\`) REFERENCES \`CampaignType\`(\`idCampaignType\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Device\` ADD CONSTRAINT \`FK_9f77830eeede75246c2dc8a9126\` FOREIGN KEY (\`idBranch\`) REFERENCES \`Branch\`(\`idBranch\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`Device\` ADD CONSTRAINT \`FK_160f33da6b221b6e27c5329ac8b\` FOREIGN KEY (\`activationStatus\`) REFERENCES \`ActivationStatus\`(\`idActivationStatus\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD CONSTRAINT \`FK_88c09574ef9d994db6f868c6eed\` FOREIGN KEY (\`idCity\`) REFERENCES \`City\`(\`idCity\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`Branch\` ADD CONSTRAINT \`FK_037082289c0af64352233ba5c70\` FOREIGN KEY (\`idMerchant\`) REFERENCES \`Merchant\`(\`idMerchant\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD CONSTRAINT \`Merchant_ibfk_2\` FOREIGN KEY (\`idSubscriptionPlan\`) REFERENCES \`SubscriptionPlan\`(\`idSubscriptionPlan\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD CONSTRAINT \`Merchant_ibfk_1\` FOREIGN KEY (\`idsubscription_status\`) REFERENCES \`subscription_status\`(\`idsubscription_status\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD CONSTRAINT \`FK_96665cd89bf5bbabc24e227b5b4\` FOREIGN KEY (\`idOnlineLoyaltyType\`) REFERENCES \`OnlineLoyaltyType\`(\`idOnlineLoyaltyType\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD CONSTRAINT \`FK_8b202431f0c8c76856dc7d144d9\` FOREIGN KEY (\`idSubscription\`) REFERENCES \`Subscription\`(\`idSubscription\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD CONSTRAINT \`FK_618a91852ef8a042edf65be90fc\` FOREIGN KEY (\`idEcommerceType\`) REFERENCES \`EcommerceType\`(\`idEcommerceType\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD CONSTRAINT \`FK_6040a287d03f40eb0cd2d6f6e7e\` FOREIGN KEY (\`idActiveLoyality\`) REFERENCES \`Campaign\`(\`idCampaign\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`Merchant\` ADD CONSTRAINT \`FK_5b97b930dfffe8baad191a195f2\` FOREIGN KEY (\`idPos\`) REFERENCES \`POS\`(\`idPOS\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`POS\` ADD CONSTRAINT \`FK_415d19240c61e4968826d9a0fb6\` FOREIGN KEY (\`idStatus\`) REFERENCES \`MerchantStatus\`(\`idMerchantStatus\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

}
