name: Trigger Aws Pipeline

on:
  push:
    branches:
      - main
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AWS CodePipeline
        uses: zulhfreelancer/aws-codepipeline-action@v1.0.7
        with:
          aws-region: 'ap-southeast-1'
          aws-access-key: AKIARSGL23EJ5J3XNEOK
          aws-secret-key: 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
          pipeline-name: test-AppPipeline-AC0CJCPENRK
