name: Trigger Aws Pipeline

on:
  push:
    branches:
      - main
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  BACKEND:
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    name: BACKEND
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AWS CodePipeline
        uses: zulhfreelancer/aws-codepipeline-action@v1.0.7
        with:
          aws-region: us-west-2
          aws-access-key: AKIARSGL23EJ5J3XNEOK
          aws-secret-key: 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
          pipeline-name: test-AppPipeline-AC0CJCPENRK

  Frontend:
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    name: FRONTEND
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AWS CodePipeline
        uses: zulhfreelancer/aws-codepipeline-action@v1.0.7
        with:
          aws-region: us-west-2
          aws-access-key: AKIARSGL23EJ5J3XNEOK
          aws-secret-key: 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
          pipeline-name: test-FrontendPipeline-A41S5WTHFOJ
